superuser:
  name: admin
  email: admin@home.lab
  password: 1q2w3e4r

ingress:
  enabled: true
  className: traefik
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
  hosts:
    - host: netbox.home.lab
      paths:
        - /
  tls:
    - secretName: netbox-tls
      hosts:
        - netbox.home.lab

postgresql:
  enabled: true
  auth:
    username: netbox
    database: netbox
    password: 1q2w3e4r

redis:
  enabled: true
  architecture: standalone

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteMany

startupProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

readinessProbe:
  timeoutSeconds: 5

workers: 2

resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
