superuser:
  name: admin
  email: admin@home.lab
  password: 1q2w3e4r

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
  hosts:
    - host: netbox.home.lab
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: netbox-tls
      hosts:
        - netbox.home.lab

postgresql:
  enabled: true
  auth:
    username: netbox
    database: netbox

redis:
  enabled: true
  architecture: standalone

persistence:
  enabled: true
  storageClass: longhorn

resources:
  requests:
    memory: 512Mi
  limits:
    memory: 1Gi
