apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://netbox-community.github.io/netbox-chart/
      chart: netbox
      targetRevision: 8.*
      helm:
        valueFiles:
          - $values/workloads/netbox/values.yaml
    - repoURL: https://github.com/sydrawat01/homelab-gitops.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
